### ISSUE TITLE
Share a benchmark

### ISSUE THREAD

**Issue by Lundez** [dievsky/kotlin-math-benchmark#5]
Hi!

Out of interest, could you share a benchmark and how it ended up?
Would be a great resource to have on say the Wiki or README

**Comment by dievsky** [comment]
Sorry for the lack of response! Yes, that might be a good idea, though I'll have to really plaster it with warnings that since I'm the maintainer of `viktor`, the results might be biased despite my best intentions.

**Comment by dievsky** [comment]
The results are published in the `README`.
